alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ll='ls -l'
alias lh='ls -lh'
alias la='ls -a'
alias lal='ls -al'
alias firewalld='firewall-cmd'
alias ssctl='systemctl'
alias firehow='firewalld --help | grep'
alias firemod='firewalld --zone=public'
